version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: babel-eslint
    versions:
    - 9.0.0
  - dependency-name: expect-enzyme
    versions:
    - 0.15.0
